/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 dalithe_persistence_of_memory.glb --transform --shadows --resolution 512 --keepmeshes --instance --types
Files: dalithe_persistence_of_memory.glb [451.54KB] > public/dalithe_persistence_of_memory-transformed.glb [293.1KB] (35%)
Author: arloopa (https://sketchfab.com/arloopa)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/dalithe-persistence-of-memory-ab3e99facbdb4d9d8661d3f07815638e
Title: Dali,The Persistence of Memory
*/

import * as THREE from 'three'
import React, { JSX, useEffect, useMemo } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    ['Extract2_04_-_Default_0']: THREE.Mesh
    Cylinder006_Ceramic_0: THREE.Mesh
    ['Box001_05_-_Default_0']: THREE.Mesh
    ['Line005_02_-_Default_0']: THREE.Mesh
    ['Cylinder003_01_-_Default_0']: THREE.Mesh
    ['Sphere003_03_-_Default_0']: THREE.Mesh
    ['Line004_16_-_Matte_Plastic_0']: THREE.Mesh
    Cylinder007_Ceramic1_0: THREE.Mesh
  }
  materials: {
    ['04_-_Default']: THREE.MeshBasicMaterial
    Ceramic: THREE.MeshBasicMaterial
    ['05_-_Default']: THREE.MeshBasicMaterial
    ['02_-_Default']: THREE.MeshBasicMaterial
    ['01_-_Default']: THREE.MeshBasicMaterial
    ['03_-_Default']: THREE.MeshBasicMaterial
    ['16_-_Matte_Plastic']: THREE.MeshBasicMaterial
    Ceramic1: THREE.MeshBasicMaterial
  }
}

type MemoryProps = JSX.IntrinsicElements['group'] & { nightScene?: boolean };

export function Memory({ nightScene = false, ...props }: MemoryProps) {
  const { nodes, materials } = useGLTF('models/dalithe_persistence_of_memory.glb') as GLTFResult
  const landscape = useMemo(() => {
    const original = nodes['Box001_05_-_Default_0'].geometry;
    if (!nightScene) return original;
    const geometry = original.clone();
    const positions = geometry.getAttribute('position');
    const indices = geometry.getIndex();
    const kept: number[] = [];
    // The slab and painted rock are disconnected parts behind z=-250
    // in the source mesh. Preserve the foreground artwork.
    const count = indices ? indices.count : positions.count;
    for (let i = 0; i < count; i += 3) {
      const a = indices ? indices.getX(i) : i;
      const b = indices ? indices.getX(i + 1) : i + 1;
      const c = indices ? indices.getX(i + 2) : i + 2;
      if (Math.max(positions.getZ(a), positions.getZ(b), positions.getZ(c)) > -240) kept.push(a, b, c);
    }
    geometry.setIndex(kept);
    return geometry;
  }, [nodes, nightScene]);
  const groundMaterial = useMemo(() => {
    if (!nightScene) return materials['16_-_Matte_Plastic'];
    const material = materials['16_-_Matte_Plastic'].clone();
    material.color.setRGB(0.55, 0.64, 0.85);
    return material;
  }, [materials, nightScene]);
  const groundBaseMaterial = useMemo(() => {
    if (!nightScene) return materials.Ceramic1;
    const material = materials.Ceramic1.clone();
    material.color.multiply(new THREE.Color().setRGB(0.55, 0.64, 0.85));
    return material;
  }, [materials, nightScene]);
  useEffect(() => () => {
    if (nightScene) {
      landscape.dispose();
      groundMaterial.dispose();
      groundBaseMaterial.dispose();
    }
  }, [landscape, groundMaterial, groundBaseMaterial, nightScene]);
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes['Extract2_04_-_Default_0'].geometry} material={materials['04_-_Default']} scale={0.021} />
      {!nightScene && <mesh castShadow receiveShadow geometry={nodes.Cylinder006_Ceramic_0.geometry} material={materials.Ceramic} position={[0.541, 0, 2.543]} rotation={[-Math.PI / 2, 0, 0]} scale={0.021} />}
      <mesh castShadow receiveShadow geometry={landscape} material={materials['05_-_Default']} scale={0.021} />
      <mesh castShadow receiveShadow geometry={nodes['Line005_02_-_Default_0'].geometry} material={materials['02_-_Default']} position={[0, 0.005, 0]} scale={0.021} />
      <mesh castShadow receiveShadow geometry={nodes['Cylinder003_01_-_Default_0'].geometry} material={materials['01_-_Default']} position={[-0.584, 0.659, -1.595]} scale={0.021} />
      <mesh castShadow receiveShadow geometry={nodes['Sphere003_03_-_Default_0'].geometry} material={materials['03_-_Default']} position={[-0.901, 0.331, -1.311]} rotation={[-Math.PI / 2, 0, 0]} scale={0.021} />
      <mesh castShadow receiveShadow geometry={nodes['Line004_16_-_Matte_Plastic_0'].geometry} material={groundMaterial} rotation={[-Math.PI / 2, 0, 0]} scale={0.021} />
      <mesh castShadow receiveShadow geometry={nodes.Cylinder007_Ceramic1_0.geometry} material={groundBaseMaterial} position={[0.541, 0, 2.543]} rotation={[-Math.PI / 2, 0, 0]} scale={0.022} />
    </group>
  )
}

useGLTF.preload('models/dalithe_persistence_of_memory.glb')
